import {
  authSession,
  defineCommand,
  exposure,
  jsonOutput,
  opaqueObjectSchema,
  arraySchema,
  stringSchema,
  booleanSchema,
  addressSchema,
  decimalStringSchema,
  writeMutation,
  objectSchema,
  unknownSchema,
} from "./helpers.js";
import type { AgwCommandDefinition } from "./types.js";

export const contractNamespaceDefinition: AgwCommandDefinition = defineCommand({
  id: "contract",
  path: ["contract"],
  kind: "namespace",
  description: "Execute contract writes and deployment flows through AGW policies.",
  status: "planned",
  inputMode: "json",
  auth: authSession("write_ready_required"),
  mutation: writeMutation(),
  output: jsonOutput(true, false),
  exposure: exposure(true, true),
  children: [
    defineCommand({
      id: "contract.write",
      path: ["contract", "write"],
      kind: "command",
      description: "Preview or execute a contract write call.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: objectSchema(
        {
          address: addressSchema("Target contract address."),
          abi: arraySchema(opaqueObjectSchema("ABI entry.")),
          functionName: stringSchema(),
          args: arraySchema(unknownSchema({ description: "Function argument payload." })),
          value: decimalStringSchema("Wei value as a decimal string."),
          execute: booleanSchema({ default: false }),
        },
        { required: ["address", "abi", "functionName"] },
      ),
      responseSchema: objectSchema({
        preview: booleanSchema(),
        requiresExplicitExecute: booleanSchema(),
        action: stringSchema(),
        txHash: stringSchema(),
        accountAddress: addressSchema("Linked AGW account address."),
        chainId: { type: "integer", minimum: 0 },
        explorer: opaqueObjectSchema("Explorer metadata."),
        contract: opaqueObjectSchema("Contract execution payload."),
      }),
      mutation: writeMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "contract.deploy",
      path: ["contract", "deploy"],
      kind: "command",
      description: "Preview or execute contract deployment through the AGW signer.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: objectSchema(
        {
          bytecode: stringSchema(),
          abi: arraySchema(opaqueObjectSchema("ABI entry.")),
          execute: booleanSchema({ default: false }),
        },
        { required: ["abi", "bytecode"] },
      ),
      responseSchema: objectSchema({
        preview: booleanSchema(),
        requiresExplicitExecute: booleanSchema(),
        execute: booleanSchema(),
        txHash: stringSchema(),
        accountAddress: addressSchema("Linked AGW account address."),
        chainId: { type: "integer", minimum: 0 },
        explorer: opaqueObjectSchema("Explorer metadata."),
        deployment: opaqueObjectSchema("Deployment result payload."),
      }),
      mutation: writeMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
    }),
  ],
});
