import { authSession, defineCommand, exposure, jsonOutput, listResponseSchema, ndjsonOutput, readMutation } from "./helpers.js";
import type { AgwCommandDefinition } from "./types.js";

export const portalNamespaceDefinition: AgwCommandDefinition = defineCommand({
  id: "portal",
  path: ["portal"],
  kind: "namespace",
  description: "Read Portal API data related to apps, streams, and user profiles.",
  status: "planned",
  inputMode: "json",
  auth: authSession("active_required"),
  mutation: readMutation(),
  output: ndjsonOutput(true, true),
  exposure: exposure(true, true),
  children: [
    defineCommand({
      id: "portal.apps",
      path: ["portal", "apps"],
      kind: "namespace",
      description: "List and inspect Portal apps.",
      status: "planned",
      inputMode: "json",
      auth: authSession("active_required"),
      mutation: readMutation(),
      output: ndjsonOutput(true, true),
      exposure: exposure(true, true),
      children: [
        defineCommand({
          id: "portal.apps.list",
          path: ["portal", "apps", "list"],
          kind: "command",
          description: "List Portal apps.",
          status: "implemented",
          inputMode: "json",
          auth: authSession("active_required"),
          requestSchema: {
            type: "object",
            properties: {
              cursor: { type: "string" },
              pageSize: { type: "number" },
              fields: { type: "array", items: { type: "string" } },
            },
          },
          responseSchema: listResponseSchema,
          mutation: readMutation(),
          output: ndjsonOutput(true, true),
          exposure: exposure(true, true, ["always page and trim Portal app lists to the fields needed for the task"]),
        }),
        defineCommand({
          id: "portal.apps.get",
          path: ["portal", "apps", "get"],
          kind: "command",
          description: "Get Portal app details.",
          status: "implemented",
          inputMode: "json",
          auth: authSession("active_required"),
          requestSchema: {
            type: "object",
            properties: {
              appId: { type: "string" },
              fields: { type: "array", items: { type: "string" } },
            },
            required: ["appId"],
          },
          responseSchema: {
            type: "object",
            properties: {
              app: { type: "object" },
            },
            required: ["app"],
          },
          mutation: readMutation(),
          output: jsonOutput(true, false),
          exposure: exposure(true, true),
        }),
      ],
    }),
    defineCommand({
      id: "portal.streams",
      path: ["portal", "streams"],
      kind: "namespace",
      description: "List Portal streams.",
      status: "planned",
      inputMode: "json",
      auth: authSession("active_required"),
      mutation: readMutation(),
      output: ndjsonOutput(true, true),
      exposure: exposure(true, true),
      children: [
        defineCommand({
          id: "portal.streams.list",
          path: ["portal", "streams", "list"],
          kind: "command",
          description: "List streams for a Portal app.",
          status: "implemented",
          inputMode: "json",
          auth: authSession("active_required"),
          requestSchema: {
            type: "object",
            properties: {
              appId: { type: "string" },
              cursor: { type: "string" },
              pageSize: { type: "number" },
              fields: { type: "array", items: { type: "string" } },
            },
            required: ["appId"],
          },
          responseSchema: listResponseSchema,
          mutation: readMutation(),
          output: ndjsonOutput(true, true),
          exposure: exposure(true, true),
        }),
      ],
    }),
    defineCommand({
      id: "portal.user-profile",
      path: ["portal", "user-profile"],
      kind: "namespace",
      description: "Inspect Portal user profiles.",
      status: "planned",
      inputMode: "json",
      auth: authSession("active_required"),
      mutation: readMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
      children: [
        defineCommand({
          id: "portal.user-profile.get",
          path: ["portal", "user-profile", "get"],
          kind: "command",
          description: "Get a Portal user profile by address.",
          status: "implemented",
          inputMode: "json",
          auth: authSession("active_required"),
          requestSchema: {
            type: "object",
            properties: {
              address: { type: "string" },
              fields: { type: "array", items: { type: "string" } },
            },
            required: ["address"],
          },
          responseSchema: {
            type: "object",
            properties: {
              profile: { type: "object" },
            },
            required: ["profile"],
          },
          mutation: readMutation(),
          output: jsonOutput(true, false),
          exposure: exposure(true, true),
        }),
      ],
    }),
  ],
});
