import {
  authSession,
  defineCommand,
  exposure,
  jsonOutput,
  opaqueObjectSchema,
  objectSchema,
  readMutation,
  booleanSchema,
  integerSchema,
  stringSchema,
  transactionRequestSchema,
  transactionResponseSchema,
  writeMutation,
} from "./helpers.js";
import type { AgwCommandDefinition } from "./types.js";

export const txNamespaceDefinition: AgwCommandDefinition = defineCommand({
  id: "tx",
  path: ["tx"],
  kind: "namespace",
  description: "Preview, sign, and execute AGW transactions with explicit execution intent.",
  status: "planned",
  inputMode: "json",
  auth: authSession("write_ready_required"),
  mutation: writeMutation(),
  output: jsonOutput(true, false),
  exposure: exposure(true, true),
  children: [
    defineCommand({
      id: "tx.preview",
      path: ["tx", "preview"],
      kind: "command",
      description: "Preview a transaction or call bundle without broadcasting.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: transactionRequestSchema,
      responseSchema: {
        type: "object",
        properties: {
          preview: { type: "boolean" },
          accountAddress: { type: "string" },
          chainId: { type: "number" },
          transaction: opaqueObjectSchema("Preview transaction payload."),
          impact: opaqueObjectSchema("Estimated transaction impact."),
          risk: opaqueObjectSchema("Transaction risk assessment."),
        },
        required: ["preview", "risk"],
      },
      mutation: readMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "tx.send",
      path: ["tx", "send"],
      kind: "command",
      description: "Send a single transaction through the AGW signer with explicit execute intent.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: transactionRequestSchema,
      responseSchema: transactionResponseSchema,
      mutation: writeMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true, ["default to preview mode and require explicit execute intent for broadcast"]),
    }),
    defineCommand({
      id: "tx.calls",
      path: ["tx", "calls"],
      kind: "command",
      description: "Send a batched call set through the AGW signer with preview-first semantics.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: objectSchema(
        {
          calls: { type: "array", items: opaqueObjectSchema("Transaction call payload.") },
          execute: booleanSchema({ default: false }),
        },
        { required: ["calls"] },
      ),
      responseSchema: objectSchema({
        preview: booleanSchema(),
        execute: booleanSchema(),
        requiresExplicitExecute: booleanSchema(),
        id: stringSchema(),
        accountAddress: stringSchema(),
        chainId: integerSchema(),
        callCount: integerSchema(),
        calls: { type: "array", items: opaqueObjectSchema("Transaction call payload.") },
      }),
      mutation: writeMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "tx.sign-message",
      path: ["tx", "sign-message"],
      kind: "command",
      description: "Sign a UTF-8 message with the AGW signer.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: objectSchema(
        {
          message: stringSchema(),
          execute: booleanSchema({ default: false }),
        },
        { required: ["message"] },
      ),
      responseSchema: objectSchema({
        preview: booleanSchema(),
        requiresExplicitExecute: booleanSchema(),
        action: stringSchema(),
        signature: stringSchema(),
        message: stringSchema(),
        accountAddress: stringSchema(),
        chainId: integerSchema(),
      }),
      mutation: {
        risk: "state_change",
        defaultMode: "preview",
        requiresExplicitExecute: true,
        supportsDryRun: true,
        supportsExecution: true,
        supportsPreview: true,
      },
      output: jsonOutput(false, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "tx.sign-transaction",
      path: ["tx", "sign-transaction"],
      kind: "command",
      description: "Sign a transaction payload without broadcasting.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: objectSchema(
        {
          to: stringSchema(),
          data: stringSchema(),
          value: stringSchema(),
          execute: booleanSchema({ default: false }),
        },
        { required: ["to", "data"] },
      ),
      responseSchema: objectSchema({
        preview: booleanSchema(),
        requiresExplicitExecute: booleanSchema(),
        action: stringSchema(),
        signedPayload: stringSchema(),
        broadcast: booleanSchema(),
        accountAddress: stringSchema(),
        chainId: integerSchema(),
        transaction: opaqueObjectSchema("Signed transaction payload."),
      }),
      mutation: {
        risk: "state_change",
        defaultMode: "preview",
        requiresExplicitExecute: true,
        supportsDryRun: true,
        supportsExecution: true,
        supportsPreview: true,
      },
      output: jsonOutput(false, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "tx.transfer-token",
      path: ["tx", "transfer-token"],
      kind: "command",
      description: "Preview or execute an ERC-20 transfer.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: objectSchema(
        {
          tokenAddress: stringSchema(),
          to: stringSchema(),
          amount: stringSchema(),
          execute: booleanSchema({ default: false }),
        },
        { required: ["to", "amount"] },
      ),
      responseSchema: objectSchema({
        preview: booleanSchema(),
        broadcast: booleanSchema(),
        requiresExplicitExecute: booleanSchema(),
        txHash: stringSchema(),
        accountAddress: stringSchema(),
        chainId: integerSchema(),
        transfer: opaqueObjectSchema("ERC-20 transfer payload."),
        explorer: opaqueObjectSchema("Explorer metadata."),
      }),
      mutation: writeMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
    }),
  ],
});
