import {
  authSession,
  defineCommand,
  exposure,
  jsonOutput,
  readMutation,
  transactionRequestSchema,
  transactionResponseSchema,
  writeMutation,
} from "./helpers.js";
import type { AgwCommandDefinition } from "./types.js";

export const txNamespaceDefinition: AgwCommandDefinition = defineCommand({
  id: "tx",
  path: ["tx"],
  kind: "namespace",
  description: "Preview, sign, and execute AGW transactions with explicit execution intent.",
  status: "planned",
  inputMode: "json",
  auth: authSession("write_ready_required"),
  mutation: writeMutation(),
  output: jsonOutput(true, false),
  exposure: exposure(true, true),
  children: [
    defineCommand({
      id: "tx.preview",
      path: ["tx", "preview"],
      kind: "command",
      description: "Preview a transaction or call bundle without broadcasting.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: transactionRequestSchema,
      responseSchema: {
        type: "object",
        properties: {
          preview: { type: "boolean" },
          accountAddress: { type: "string" },
          chainId: { type: "number" },
          transaction: { type: "object" },
          impact: { type: "object" },
          risk: { type: "object" },
        },
        required: ["preview", "risk"],
      },
      mutation: readMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "tx.send",
      path: ["tx", "send"],
      kind: "command",
      description: "Send a single transaction through the AGW signer with explicit execute intent.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: transactionRequestSchema,
      responseSchema: transactionResponseSchema,
      mutation: writeMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true, ["default to preview mode and require explicit execute intent for broadcast"]),
    }),
    defineCommand({
      id: "tx.calls",
      path: ["tx", "calls"],
      kind: "command",
      description: "Send a batched call set through the AGW signer with preview-first semantics.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: {
        type: "object",
        properties: {
          calls: { type: "array" },
          execute: { type: "boolean", default: false },
        },
        required: ["calls"],
      },
      responseSchema: {
        type: "object",
        properties: {
          preview: { type: "boolean" },
          execute: { type: "boolean" },
          requiresExplicitExecute: { type: "boolean" },
          id: { type: "string" },
          accountAddress: { type: "string" },
          chainId: { type: "number" },
          callCount: { type: "number" },
          calls: { type: "array" },
        },
      },
      mutation: writeMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "tx.sign-message",
      path: ["tx", "sign-message"],
      kind: "command",
      description: "Sign a UTF-8 message with the AGW signer.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: {
        type: "object",
        properties: {
          message: { type: "string" },
          execute: { type: "boolean", default: false },
        },
        required: ["message"],
      },
      responseSchema: {
        type: "object",
        properties: {
          preview: { type: "boolean" },
          requiresExplicitExecute: { type: "boolean" },
          action: { type: "string" },
          signature: { type: "string" },
          message: { type: "string" },
          accountAddress: { type: "string" },
          chainId: { type: "number" },
        },
      },
      mutation: {
        risk: "state_change",
        requiresExplicitExecute: true,
        supportsDryRun: false,
      },
      output: jsonOutput(false, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "tx.sign-transaction",
      path: ["tx", "sign-transaction"],
      kind: "command",
      description: "Sign a transaction payload without broadcasting.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: {
        type: "object",
        properties: {
          to: { type: "string" },
          data: { type: "string" },
          value: { type: "string" },
          execute: { type: "boolean", default: false },
        },
        required: ["to", "data"],
      },
      responseSchema: {
        type: "object",
        properties: {
          preview: { type: "boolean" },
          requiresExplicitExecute: { type: "boolean" },
          action: { type: "string" },
          signedPayload: { type: "string" },
          broadcast: { type: "boolean" },
          accountAddress: { type: "string" },
          chainId: { type: "number" },
          transaction: { type: "object" },
        },
      },
      mutation: {
        risk: "state_change",
        requiresExplicitExecute: true,
        supportsDryRun: false,
      },
      output: jsonOutput(false, false),
      exposure: exposure(true, true),
    }),
    defineCommand({
      id: "tx.transfer-token",
      path: ["tx", "transfer-token"],
      kind: "command",
      description: "Preview or execute an ERC-20 transfer.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("write_ready_required"),
      requestSchema: {
        type: "object",
        properties: {
          tokenAddress: { type: "string" },
          to: { type: "string" },
          amount: { type: "string" },
          execute: { type: "boolean", default: false },
        },
        required: ["to", "amount"],
      },
      responseSchema: {
        type: "object",
        properties: {
          preview: { type: "boolean" },
          broadcast: { type: "boolean" },
          requiresExplicitExecute: { type: "boolean" },
          txHash: { type: "string" },
          accountAddress: { type: "string" },
          chainId: { type: "number" },
          transfer: { type: "object" },
          explorer: { type: "object" },
        },
      },
      mutation: writeMutation(),
      output: jsonOutput(true, false),
      exposure: exposure(true, true),
    }),
  ],
});
