import {
  addressSchema,
  authSession,
  config,
  defineCommand,
  emptyObjectSchema,
  exposure,
  fieldsSchema,
  integerSchema,
  jsonOutput,
  listResponseSchema,
  ndjsonOutput,
  objectSchema,
  opaqueObjectSchema,
  paginationRequestSchema,
  readMutation,
  sanitize,
  stringSchema,
} from "./helpers.js";
import type { AgwCommandDefinition } from "./types.js";

export const walletNamespaceDefinition: AgwCommandDefinition = defineCommand({
  id: "wallet",
  path: ["wallet"],
  kind: "namespace",
  description: "Read wallet identity, balances, and token inventory.",
  status: "planned",
  inputMode: "json",
  auth: authSession("active_required"),
  mutation: readMutation(),
  output: ndjsonOutput(true, true),
  exposure: exposure(true, true),
  children: [
    defineCommand({
      id: "wallet.address",
      path: ["wallet", "address"],
      kind: "command",
      description: "Return the linked AGW account address.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("active_required"),
      requestSchema: emptyObjectSchema(),
      responseSchema: objectSchema(
        {
          accountAddress: addressSchema("Linked AGW account address."),
          chainId: integerSchema(),
        },
        { required: ["accountAddress", "chainId"] },
      ),
      mutation: readMutation(),
      output: jsonOutput(true, false),
      sanitization: sanitize(false),
      exposure: exposure(true, true),
      config: config({ env: "AGW_HOME", description: "AGW home directory for local session state." }),
    }),
    defineCommand({
      id: "wallet.balances",
      path: ["wallet", "balances"],
      kind: "command",
      description: "Return native and token balances for the linked AGW account.",
      status: "implemented",
      inputMode: "json",
      auth: authSession("active_required"),
      requestSchema: objectSchema({
        fields: fieldsSchema(),
      }),
      responseSchema: objectSchema(
        {
          accountAddress: addressSchema("Linked AGW account address."),
          chainId: integerSchema(),
          balances: {
            type: "array",
            items: objectSchema(
              {
                symbol: stringSchema(),
                balance: stringSchema(),
                tokenAddress: addressSchema("Token contract address."),
                decimals: integerSchema(),
                formattedBalance: stringSchema(),
              },
              { additionalProperties: true },
            ),
          },
        },
        { required: ["accountAddress", "chainId", "balances"] },
      ),
      mutation: readMutation(),
      output: jsonOutput(true, false),
      sanitization: sanitize(false),
      exposure: exposure(true, true, ["add field selection to avoid returning unneeded balance fields"]),
      config: config(
        { env: "AGW_HOME", description: "AGW home directory for local session state." },
        { env: "AGW_CHAIN_ID", description: "Default chain id for wallet reads." },
        { env: "AGW_RPC_URL", description: "Optional RPC URL override for wallet reads." },
      ),
    }),
    defineCommand({
      id: "wallet.tokens",
      path: ["wallet", "tokens"],
      kind: "namespace",
      description: "Read token inventory with response-shaping options for agent-safe reads.",
      status: "planned",
      inputMode: "json",
      auth: authSession("active_required"),
      mutation: readMutation(),
      output: ndjsonOutput(true, true),
      exposure: exposure(true, true),
      children: [
        defineCommand({
          id: "wallet.tokens.list",
          path: ["wallet", "tokens", "list"],
          kind: "command",
          description: "Return token inventory with response-shaping options for agent-safe reads.",
          status: "implemented",
          inputMode: "json",
          auth: authSession("active_required"),
          requestSchema: objectSchema({
            ...paginationRequestSchema().properties,
            fields: fieldsSchema(),
          }),
          responseSchema: listResponseSchema(
            objectSchema(
              {
                token: opaqueObjectSchema("Token metadata payload."),
                tokenAddress: addressSchema("Token contract address."),
                balance: stringSchema(),
                rawBalance: stringSchema(),
                decimals: integerSchema(),
                formattedBalance: stringSchema(),
              },
              { additionalProperties: true },
            ),
          ),
          mutation: readMutation(),
          output: ndjsonOutput(true, true),
          sanitization: sanitize(false),
          exposure: exposure(true, true, ["prefer NDJSON pagination for large token inventories"]),
          config: config(
            { env: "AGW_HOME", description: "AGW home directory for local session state." },
            { env: "AGW_CHAIN_ID", description: "Default chain id for wallet reads." },
            { env: "AGW_RPC_URL", description: "Optional RPC URL override for wallet reads." },
          ),
        }),
      ],
    }),
  ],
});
